// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/PodPloy/podploy/internal/domain/ent/organization"
	"github.com/PodPloy/podploy/internal/domain/ent/organizationmember"
	"github.com/PodPloy/podploy/internal/domain/ent/permission"
	"github.com/PodPloy/podploy/internal/domain/ent/role"
	"github.com/PodPloy/podploy/internal/domain/ent/users"
)

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *OrganizationQuery) CollectFields(ctx context.Context, satisfies ...string) (*OrganizationQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *OrganizationQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(organization.Columns))
		selectedFields = []string{organization.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "roles":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&RoleClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, roleImplementors)...); err != nil {
				return err
			}
			_q.WithNamedRoles(alias, func(wq *RoleQuery) {
				*wq = *query
			})

		case "memberships":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&OrganizationMemberClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, organizationmemberImplementors)...); err != nil {
				return err
			}
			_q.WithNamedMemberships(alias, func(wq *OrganizationMemberQuery) {
				*wq = *query
			})
		case "name":
			if _, ok := fieldSeen[organization.FieldName]; !ok {
				selectedFields = append(selectedFields, organization.FieldName)
				fieldSeen[organization.FieldName] = struct{}{}
			}
		case "slug":
			if _, ok := fieldSeen[organization.FieldSlug]; !ok {
				selectedFields = append(selectedFields, organization.FieldSlug)
				fieldSeen[organization.FieldSlug] = struct{}{}
			}
		case "active":
			if _, ok := fieldSeen[organization.FieldActive]; !ok {
				selectedFields = append(selectedFields, organization.FieldActive)
				fieldSeen[organization.FieldActive] = struct{}{}
			}
		case "createdAt":
			if _, ok := fieldSeen[organization.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, organization.FieldCreatedAt)
				fieldSeen[organization.FieldCreatedAt] = struct{}{}
			}
		case "updatedAt":
			if _, ok := fieldSeen[organization.FieldUpdatedAt]; !ok {
				selectedFields = append(selectedFields, organization.FieldUpdatedAt)
				fieldSeen[organization.FieldUpdatedAt] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type organizationPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []OrganizationPaginateOption
}

func newOrganizationPaginateArgs(rv map[string]any) *organizationPaginateArgs {
	args := &organizationPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*OrganizationWhereInput); ok {
		args.opts = append(args.opts, WithOrganizationFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *OrganizationMemberQuery) CollectFields(ctx context.Context, satisfies ...string) (*OrganizationMemberQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *OrganizationMemberQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(organizationmember.Columns))
		selectedFields = []string{organizationmember.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "user":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&UsersClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, usersImplementors)...); err != nil {
				return err
			}
			_q.withUser = query
			if _, ok := fieldSeen[organizationmember.FieldUserID]; !ok {
				selectedFields = append(selectedFields, organizationmember.FieldUserID)
				fieldSeen[organizationmember.FieldUserID] = struct{}{}
			}

		case "organization":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&OrganizationClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, organizationImplementors)...); err != nil {
				return err
			}
			_q.withOrganization = query
			if _, ok := fieldSeen[organizationmember.FieldOrganizationID]; !ok {
				selectedFields = append(selectedFields, organizationmember.FieldOrganizationID)
				fieldSeen[organizationmember.FieldOrganizationID] = struct{}{}
			}

		case "role":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&RoleClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, roleImplementors)...); err != nil {
				return err
			}
			_q.withRole = query
			if _, ok := fieldSeen[organizationmember.FieldRoleID]; !ok {
				selectedFields = append(selectedFields, organizationmember.FieldRoleID)
				fieldSeen[organizationmember.FieldRoleID] = struct{}{}
			}
		case "userID":
			if _, ok := fieldSeen[organizationmember.FieldUserID]; !ok {
				selectedFields = append(selectedFields, organizationmember.FieldUserID)
				fieldSeen[organizationmember.FieldUserID] = struct{}{}
			}
		case "organizationID":
			if _, ok := fieldSeen[organizationmember.FieldOrganizationID]; !ok {
				selectedFields = append(selectedFields, organizationmember.FieldOrganizationID)
				fieldSeen[organizationmember.FieldOrganizationID] = struct{}{}
			}
		case "roleID":
			if _, ok := fieldSeen[organizationmember.FieldRoleID]; !ok {
				selectedFields = append(selectedFields, organizationmember.FieldRoleID)
				fieldSeen[organizationmember.FieldRoleID] = struct{}{}
			}
		case "joinedAt":
			if _, ok := fieldSeen[organizationmember.FieldJoinedAt]; !ok {
				selectedFields = append(selectedFields, organizationmember.FieldJoinedAt)
				fieldSeen[organizationmember.FieldJoinedAt] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type organizationmemberPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []OrganizationMemberPaginateOption
}

func newOrganizationMemberPaginateArgs(rv map[string]any) *organizationmemberPaginateArgs {
	args := &organizationmemberPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*OrganizationMemberWhereInput); ok {
		args.opts = append(args.opts, WithOrganizationMemberFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *PermissionQuery) CollectFields(ctx context.Context, satisfies ...string) (*PermissionQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *PermissionQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(permission.Columns))
		selectedFields = []string{permission.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "roles":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&RoleClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, roleImplementors)...); err != nil {
				return err
			}
			_q.WithNamedRoles(alias, func(wq *RoleQuery) {
				*wq = *query
			})
		case "name":
			if _, ok := fieldSeen[permission.FieldName]; !ok {
				selectedFields = append(selectedFields, permission.FieldName)
				fieldSeen[permission.FieldName] = struct{}{}
			}
		case "resource":
			if _, ok := fieldSeen[permission.FieldResource]; !ok {
				selectedFields = append(selectedFields, permission.FieldResource)
				fieldSeen[permission.FieldResource] = struct{}{}
			}
		case "action":
			if _, ok := fieldSeen[permission.FieldAction]; !ok {
				selectedFields = append(selectedFields, permission.FieldAction)
				fieldSeen[permission.FieldAction] = struct{}{}
			}
		case "createdAt":
			if _, ok := fieldSeen[permission.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, permission.FieldCreatedAt)
				fieldSeen[permission.FieldCreatedAt] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type permissionPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []PermissionPaginateOption
}

func newPermissionPaginateArgs(rv map[string]any) *permissionPaginateArgs {
	args := &permissionPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*PermissionWhereInput); ok {
		args.opts = append(args.opts, WithPermissionFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *RoleQuery) CollectFields(ctx context.Context, satisfies ...string) (*RoleQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *RoleQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(role.Columns))
		selectedFields = []string{role.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "organization":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&OrganizationClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, organizationImplementors)...); err != nil {
				return err
			}
			_q.withOrganization = query
			if _, ok := fieldSeen[role.FieldOrganizationID]; !ok {
				selectedFields = append(selectedFields, role.FieldOrganizationID)
				fieldSeen[role.FieldOrganizationID] = struct{}{}
			}

		case "memberships":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&OrganizationMemberClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, organizationmemberImplementors)...); err != nil {
				return err
			}
			_q.WithNamedMemberships(alias, func(wq *OrganizationMemberQuery) {
				*wq = *query
			})

		case "permissions":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&PermissionClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, permissionImplementors)...); err != nil {
				return err
			}
			_q.WithNamedPermissions(alias, func(wq *PermissionQuery) {
				*wq = *query
			})
		case "name":
			if _, ok := fieldSeen[role.FieldName]; !ok {
				selectedFields = append(selectedFields, role.FieldName)
				fieldSeen[role.FieldName] = struct{}{}
			}
		case "description":
			if _, ok := fieldSeen[role.FieldDescription]; !ok {
				selectedFields = append(selectedFields, role.FieldDescription)
				fieldSeen[role.FieldDescription] = struct{}{}
			}
		case "isSystem":
			if _, ok := fieldSeen[role.FieldIsSystem]; !ok {
				selectedFields = append(selectedFields, role.FieldIsSystem)
				fieldSeen[role.FieldIsSystem] = struct{}{}
			}
		case "organizationID":
			if _, ok := fieldSeen[role.FieldOrganizationID]; !ok {
				selectedFields = append(selectedFields, role.FieldOrganizationID)
				fieldSeen[role.FieldOrganizationID] = struct{}{}
			}
		case "createdAt":
			if _, ok := fieldSeen[role.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, role.FieldCreatedAt)
				fieldSeen[role.FieldCreatedAt] = struct{}{}
			}
		case "updatedAt":
			if _, ok := fieldSeen[role.FieldUpdatedAt]; !ok {
				selectedFields = append(selectedFields, role.FieldUpdatedAt)
				fieldSeen[role.FieldUpdatedAt] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type rolePaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []RolePaginateOption
}

func newRolePaginateArgs(rv map[string]any) *rolePaginateArgs {
	args := &rolePaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*RoleWhereInput); ok {
		args.opts = append(args.opts, WithRoleFilter(v.Filter))
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *UsersQuery) CollectFields(ctx context.Context, satisfies ...string) (*UsersQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *UsersQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(users.Columns))
		selectedFields = []string{users.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "memberships":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&OrganizationMemberClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, organizationmemberImplementors)...); err != nil {
				return err
			}
			_q.WithNamedMemberships(alias, func(wq *OrganizationMemberQuery) {
				*wq = *query
			})
		case "email":
			if _, ok := fieldSeen[users.FieldEmail]; !ok {
				selectedFields = append(selectedFields, users.FieldEmail)
				fieldSeen[users.FieldEmail] = struct{}{}
			}
		case "passwordHash":
			if _, ok := fieldSeen[users.FieldPasswordHash]; !ok {
				selectedFields = append(selectedFields, users.FieldPasswordHash)
				fieldSeen[users.FieldPasswordHash] = struct{}{}
			}
		case "fullName":
			if _, ok := fieldSeen[users.FieldFullName]; !ok {
				selectedFields = append(selectedFields, users.FieldFullName)
				fieldSeen[users.FieldFullName] = struct{}{}
			}
		case "active":
			if _, ok := fieldSeen[users.FieldActive]; !ok {
				selectedFields = append(selectedFields, users.FieldActive)
				fieldSeen[users.FieldActive] = struct{}{}
			}
		case "createdAt":
			if _, ok := fieldSeen[users.FieldCreatedAt]; !ok {
				selectedFields = append(selectedFields, users.FieldCreatedAt)
				fieldSeen[users.FieldCreatedAt] = struct{}{}
			}
		case "updatedAt":
			if _, ok := fieldSeen[users.FieldUpdatedAt]; !ok {
				selectedFields = append(selectedFields, users.FieldUpdatedAt)
				fieldSeen[users.FieldUpdatedAt] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type usersPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []UsersPaginateOption
}

func newUsersPaginateArgs(rv map[string]any) *usersPaginateArgs {
	args := &usersPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[whereField].(*UsersWhereInput); ok {
		args.opts = append(args.opts, WithUsersFilter(v.Filter))
	}
	return args
}

const (
	afterField     = "after"
	firstField     = "first"
	beforeField    = "before"
	lastField      = "last"
	orderByField   = "orderBy"
	directionField = "direction"
	fieldField     = "field"
	whereField     = "where"
)

func fieldArgs(ctx context.Context, whereInput any, path ...string) map[string]any {
	field := collectedField(ctx, path...)
	if field == nil || field.Arguments == nil {
		return nil
	}
	oc := graphql.GetOperationContext(ctx)
	args := field.ArgumentMap(oc.Variables)
	return unmarshalArgs(ctx, whereInput, args)
}

// unmarshalArgs allows extracting the field arguments from their raw representation.
func unmarshalArgs(ctx context.Context, whereInput any, args map[string]any) map[string]any {
	for _, k := range []string{firstField, lastField} {
		v, ok := args[k]
		if !ok || v == nil {
			continue
		}
		i, err := graphql.UnmarshalInt(v)
		if err == nil {
			args[k] = &i
		}
	}
	for _, k := range []string{beforeField, afterField} {
		v, ok := args[k]
		if !ok {
			continue
		}
		c := &Cursor{}
		if c.UnmarshalGQL(v) == nil {
			args[k] = c
		}
	}
	if v, ok := args[whereField]; ok && whereInput != nil {
		if err := graphql.UnmarshalInputFromContext(ctx, v, whereInput); err == nil {
			args[whereField] = whereInput
		}
	}

	return args
}

// mayAddCondition appends another type condition to the satisfies list
// if it does not exist in the list.
func mayAddCondition(satisfies []string, typeCond []string) []string {
Cond:
	for _, c := range typeCond {
		for _, s := range satisfies {
			if c == s {
				continue Cond
			}
		}
		satisfies = append(satisfies, c)
	}
	return satisfies
}
