// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (_m *Organization) Roles(ctx context.Context) (result []*Role, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedRoles(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.RolesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryRoles().All(ctx)
	}
	return result, err
}

func (_m *Organization) Memberships(ctx context.Context) (result []*OrganizationMember, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedMemberships(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.MembershipsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryMemberships().All(ctx)
	}
	return result, err
}

func (_m *OrganizationMember) User(ctx context.Context) (*Users, error) {
	result, err := _m.Edges.UserOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryUser().Only(ctx)
	}
	return result, err
}

func (_m *OrganizationMember) Organization(ctx context.Context) (*Organization, error) {
	result, err := _m.Edges.OrganizationOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryOrganization().Only(ctx)
	}
	return result, err
}

func (_m *OrganizationMember) Role(ctx context.Context) (*Role, error) {
	result, err := _m.Edges.RoleOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryRole().Only(ctx)
	}
	return result, err
}

func (_m *Permission) Roles(ctx context.Context) (result []*Role, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedRoles(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.RolesOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryRoles().All(ctx)
	}
	return result, err
}

func (_m *Role) Organization(ctx context.Context) (*Organization, error) {
	result, err := _m.Edges.OrganizationOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryOrganization().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (_m *Role) Memberships(ctx context.Context) (result []*OrganizationMember, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedMemberships(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.MembershipsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryMemberships().All(ctx)
	}
	return result, err
}

func (_m *Role) Permissions(ctx context.Context) (result []*Permission, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedPermissions(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.PermissionsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryPermissions().All(ctx)
	}
	return result, err
}

func (_m *Users) Memberships(ctx context.Context) (result []*OrganizationMember, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedMemberships(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.MembershipsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryMemberships().All(ctx)
	}
	return result, err
}
