// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PodPloy/podploy/internal/domain/ent/organizationmember"
	"github.com/PodPloy/podploy/internal/domain/ent/predicate"
	"github.com/PodPloy/podploy/internal/domain/ent/users"
	"github.com/google/uuid"
)

// UsersUpdate is the builder for updating Users entities.
type UsersUpdate struct {
	config
	hooks    []Hook
	mutation *UsersMutation
}

// Where appends a list predicates to the UsersUpdate builder.
func (_u *UsersUpdate) Where(ps ...predicate.Users) *UsersUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEmail sets the "email" field.
func (_u *UsersUpdate) SetEmail(v string) *UsersUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UsersUpdate) SetNillableEmail(v *string) *UsersUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UsersUpdate) SetPasswordHash(v string) *UsersUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UsersUpdate) SetNillablePasswordHash(v *string) *UsersUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetFullName sets the "full_name" field.
func (_u *UsersUpdate) SetFullName(v string) *UsersUpdate {
	_u.mutation.SetFullName(v)
	return _u
}

// SetNillableFullName sets the "full_name" field if the given value is not nil.
func (_u *UsersUpdate) SetNillableFullName(v *string) *UsersUpdate {
	if v != nil {
		_u.SetFullName(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *UsersUpdate) SetActive(v bool) *UsersUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *UsersUpdate) SetNillableActive(v *bool) *UsersUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UsersUpdate) SetUpdatedAt(v time.Time) *UsersUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddMembershipIDs adds the "memberships" edge to the OrganizationMember entity by IDs.
func (_u *UsersUpdate) AddMembershipIDs(ids ...uuid.UUID) *UsersUpdate {
	_u.mutation.AddMembershipIDs(ids...)
	return _u
}

// AddMemberships adds the "memberships" edges to the OrganizationMember entity.
func (_u *UsersUpdate) AddMemberships(v ...*OrganizationMember) *UsersUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMembershipIDs(ids...)
}

// Mutation returns the UsersMutation object of the builder.
func (_u *UsersUpdate) Mutation() *UsersMutation {
	return _u.mutation
}

// ClearMemberships clears all "memberships" edges to the OrganizationMember entity.
func (_u *UsersUpdate) ClearMemberships() *UsersUpdate {
	_u.mutation.ClearMemberships()
	return _u
}

// RemoveMembershipIDs removes the "memberships" edge to OrganizationMember entities by IDs.
func (_u *UsersUpdate) RemoveMembershipIDs(ids ...uuid.UUID) *UsersUpdate {
	_u.mutation.RemoveMembershipIDs(ids...)
	return _u
}

// RemoveMemberships removes "memberships" edges to OrganizationMember entities.
func (_u *UsersUpdate) RemoveMemberships(v ...*OrganizationMember) *UsersUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMembershipIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UsersUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsersUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UsersUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsersUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UsersUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := users.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsersUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := users.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Users.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordHash(); ok {
		if err := users.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "Users.password_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FullName(); ok {
		if err := users.FullNameValidator(v); err != nil {
			return &ValidationError{Name: "full_name", err: fmt.Errorf(`ent: validator failed for field "Users.full_name": %w`, err)}
		}
	}
	return nil
}

func (_u *UsersUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(users.Table, users.Columns, sqlgraph.NewFieldSpec(users.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(users.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(users.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.FullName(); ok {
		_spec.SetField(users.FieldFullName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(users.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(users.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   users.MembershipsTable,
			Columns: []string{users.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationmember.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembershipsIDs(); len(nodes) > 0 && !_u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   users.MembershipsTable,
			Columns: []string{users.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationmember.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   users.MembershipsTable,
			Columns: []string{users.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationmember.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{users.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UsersUpdateOne is the builder for updating a single Users entity.
type UsersUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UsersMutation
}

// SetEmail sets the "email" field.
func (_u *UsersUpdateOne) SetEmail(v string) *UsersUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UsersUpdateOne) SetNillableEmail(v *string) *UsersUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UsersUpdateOne) SetPasswordHash(v string) *UsersUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UsersUpdateOne) SetNillablePasswordHash(v *string) *UsersUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetFullName sets the "full_name" field.
func (_u *UsersUpdateOne) SetFullName(v string) *UsersUpdateOne {
	_u.mutation.SetFullName(v)
	return _u
}

// SetNillableFullName sets the "full_name" field if the given value is not nil.
func (_u *UsersUpdateOne) SetNillableFullName(v *string) *UsersUpdateOne {
	if v != nil {
		_u.SetFullName(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *UsersUpdateOne) SetActive(v bool) *UsersUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *UsersUpdateOne) SetNillableActive(v *bool) *UsersUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UsersUpdateOne) SetUpdatedAt(v time.Time) *UsersUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddMembershipIDs adds the "memberships" edge to the OrganizationMember entity by IDs.
func (_u *UsersUpdateOne) AddMembershipIDs(ids ...uuid.UUID) *UsersUpdateOne {
	_u.mutation.AddMembershipIDs(ids...)
	return _u
}

// AddMemberships adds the "memberships" edges to the OrganizationMember entity.
func (_u *UsersUpdateOne) AddMemberships(v ...*OrganizationMember) *UsersUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMembershipIDs(ids...)
}

// Mutation returns the UsersMutation object of the builder.
func (_u *UsersUpdateOne) Mutation() *UsersMutation {
	return _u.mutation
}

// ClearMemberships clears all "memberships" edges to the OrganizationMember entity.
func (_u *UsersUpdateOne) ClearMemberships() *UsersUpdateOne {
	_u.mutation.ClearMemberships()
	return _u
}

// RemoveMembershipIDs removes the "memberships" edge to OrganizationMember entities by IDs.
func (_u *UsersUpdateOne) RemoveMembershipIDs(ids ...uuid.UUID) *UsersUpdateOne {
	_u.mutation.RemoveMembershipIDs(ids...)
	return _u
}

// RemoveMemberships removes "memberships" edges to OrganizationMember entities.
func (_u *UsersUpdateOne) RemoveMemberships(v ...*OrganizationMember) *UsersUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMembershipIDs(ids...)
}

// Where appends a list predicates to the UsersUpdate builder.
func (_u *UsersUpdateOne) Where(ps ...predicate.Users) *UsersUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UsersUpdateOne) Select(field string, fields ...string) *UsersUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Users entity.
func (_u *UsersUpdateOne) Save(ctx context.Context) (*Users, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsersUpdateOne) SaveX(ctx context.Context) *Users {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UsersUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsersUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UsersUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := users.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsersUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := users.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Users.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordHash(); ok {
		if err := users.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "Users.password_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FullName(); ok {
		if err := users.FullNameValidator(v); err != nil {
			return &ValidationError{Name: "full_name", err: fmt.Errorf(`ent: validator failed for field "Users.full_name": %w`, err)}
		}
	}
	return nil
}

func (_u *UsersUpdateOne) sqlSave(ctx context.Context) (_node *Users, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(users.Table, users.Columns, sqlgraph.NewFieldSpec(users.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Users.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, users.FieldID)
		for _, f := range fields {
			if !users.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != users.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(users.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(users.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.FullName(); ok {
		_spec.SetField(users.FieldFullName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(users.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(users.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   users.MembershipsTable,
			Columns: []string{users.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationmember.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembershipsIDs(); len(nodes) > 0 && !_u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   users.MembershipsTable,
			Columns: []string{users.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationmember.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   users.MembershipsTable,
			Columns: []string{users.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationmember.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Users{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{users.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
