// Code generated by ent, DO NOT EDIT.

package models

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/PodPloy/podploy/internal/domain/models/organization"
	"github.com/PodPloy/podploy/internal/domain/models/organizationmember"
	"github.com/PodPloy/podploy/internal/domain/models/role"
	"github.com/PodPloy/podploy/internal/domain/models/users"
	"github.com/google/uuid"
)

// OrganizationMember is the model entity for the OrganizationMember schema.
type OrganizationMember struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// OrganizationID holds the value of the "organization_id" field.
	OrganizationID uuid.UUID `json:"organization_id,omitempty"`
	// RoleID holds the value of the "role_id" field.
	RoleID uuid.UUID `json:"role_id,omitempty"`
	// JoinedAt holds the value of the "joined_at" field.
	JoinedAt time.Time `json:"joined_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OrganizationMemberQuery when eager-loading is set.
	Edges        OrganizationMemberEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OrganizationMemberEdges holds the relations/edges for other nodes in the graph.
type OrganizationMemberEdges struct {
	// User holds the value of the user edge.
	User *Users `json:"user,omitempty"`
	// Organization holds the value of the organization edge.
	Organization *Organization `json:"organization,omitempty"`
	// Role holds the value of the role edge.
	Role *Role `json:"role,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OrganizationMemberEdges) UserOrErr() (*Users, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: users.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// OrganizationOrErr returns the Organization value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OrganizationMemberEdges) OrganizationOrErr() (*Organization, error) {
	if e.Organization != nil {
		return e.Organization, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: organization.Label}
	}
	return nil, &NotLoadedError{edge: "organization"}
}

// RoleOrErr returns the Role value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OrganizationMemberEdges) RoleOrErr() (*Role, error) {
	if e.Role != nil {
		return e.Role, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: role.Label}
	}
	return nil, &NotLoadedError{edge: "role"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OrganizationMember) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case organizationmember.FieldID:
			values[i] = new(sql.NullInt64)
		case organizationmember.FieldJoinedAt:
			values[i] = new(sql.NullTime)
		case organizationmember.FieldUserID, organizationmember.FieldOrganizationID, organizationmember.FieldRoleID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OrganizationMember fields.
func (_m *OrganizationMember) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case organizationmember.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case organizationmember.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case organizationmember.FieldOrganizationID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field organization_id", values[i])
			} else if value != nil {
				_m.OrganizationID = *value
			}
		case organizationmember.FieldRoleID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field role_id", values[i])
			} else if value != nil {
				_m.RoleID = *value
			}
		case organizationmember.FieldJoinedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field joined_at", values[i])
			} else if value.Valid {
				_m.JoinedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OrganizationMember.
// This includes values selected through modifiers, order, etc.
func (_m *OrganizationMember) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the OrganizationMember entity.
func (_m *OrganizationMember) QueryUser() *UsersQuery {
	return NewOrganizationMemberClient(_m.config).QueryUser(_m)
}

// QueryOrganization queries the "organization" edge of the OrganizationMember entity.
func (_m *OrganizationMember) QueryOrganization() *OrganizationQuery {
	return NewOrganizationMemberClient(_m.config).QueryOrganization(_m)
}

// QueryRole queries the "role" edge of the OrganizationMember entity.
func (_m *OrganizationMember) QueryRole() *RoleQuery {
	return NewOrganizationMemberClient(_m.config).QueryRole(_m)
}

// Update returns a builder for updating this OrganizationMember.
// Note that you need to call OrganizationMember.Unwrap() before calling this method if this OrganizationMember
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OrganizationMember) Update() *OrganizationMemberUpdateOne {
	return NewOrganizationMemberClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OrganizationMember entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OrganizationMember) Unwrap() *OrganizationMember {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("models: OrganizationMember is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OrganizationMember) String() string {
	var builder strings.Builder
	builder.WriteString("OrganizationMember(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("organization_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrganizationID))
	builder.WriteString(", ")
	builder.WriteString("role_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RoleID))
	builder.WriteString(", ")
	builder.WriteString("joined_at=")
	builder.WriteString(_m.JoinedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OrganizationMembers is a parsable slice of OrganizationMember.
type OrganizationMembers []*OrganizationMember
