// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Organization is the predicate function for organization builders.
type Organization func(*sql.Selector)

// OrganizationMember is the predicate function for organizationmember builders.
type OrganizationMember func(*sql.Selector)

// Permission is the predicate function for permission builders.
type Permission func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// Users is the predicate function for users builders.
type Users func(*sql.Selector)
